services:
  - type: web
    name: stock-frontend
    env: static
    buildCommand: cd stock-frontend && npm install && npm run build
    staticPublishPath: ./stock-frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html